const TALWARAJI_TRACK_LINKS=[
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Aao sakhee har meyl kareyhaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Aapeh meyl ley.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Aeeh Sant Pauraneh.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Aiso sahaaee har ko naam - 1960s.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Aithhai Othhai mukat hai jin raam pachhaaney.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Amrit peevoh sadaa chir jeevoh.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Anand Karaj.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Anoop padaarath naam sunoh.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Antar kapatt chukaavoh meyrey gursikhoh.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Apney satgur kee vaddiaaee.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Aree baaee gobind naam mat beesrai.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Asso Rae Har Ras Meethaa - Ludhiana Smagam.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Baabaa man mathavaaro naam ras peevai.MP3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Baabaa man matvaaro.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Bhaaee rey mo kau koee aaey milai har naam drirhaavai - 1984.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Bhagtaa kee tteyk toon.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Bin teyl deevaa kio jalai.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Eis grih mehi koee jaagath rehai.MP3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Eyh man naam nidhaan too paaey.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Eyk cheej mujhai deyh.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Feekae har kae naam bin saadh.MP3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Gur meyree poojaa gur gobind.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Gur parsaadee paaiaa jaaey.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Gur saakhee antar jaagee.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Gur saakhee jot jagaaey deeva baaliaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Gurmukh laahaa lai gaey.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Gursikhaa jaikaar satgur paaiaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Habh koorraavey kanm ikas saaee baaharey.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Ham hovat cheyree daas daasan kee.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Har anmrit paan karoh saadhsang.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Har cheyt acheyt manaa - 1986.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Har key sang basey - 1986.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Har prabh kaaj rachaaeiaa - Dehli Rainsbhai 1991.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Har Prabh Kaaj Rachaiaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Jaikaar keeo dharameeaa kaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Jin Har Meet Lagana - India 1980s.MP3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Jin jan gurmukh seviaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Jinee sach vananjiaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Khaae Jeevahu Sikh Paravaar.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Khaaey jeevoh sikh parvaar.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Lakh Khusheaan Patsheeaa - 1982.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Maaee ree man meyro matvaaro.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Maeraa sathigur piaaraa kith bidhh milai.MP3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Maeraa satigur piaaraa kith bidhh milai 2.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Mai man vaddee aas harey.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Man bairaagee kio n araadhhae - Delhi 2003.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Man kio bairaag kurehigaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Man meetth tuhaaro keeo.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Man meyraa diaal seytee thir na rahai.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Mat bhooleh rey man cheyt haree.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Meyraa man laagaa hai.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Meyree sakhee saheylarheeo.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Meyrey raam ham baarik har prabh key.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Meyrey satgur apney baalak raakho - 1990.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Naam japandarhee laalee.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Naam Ras Peevai - India 1980s.MP3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Ouddahu n kaagaa kaarae - 1960s.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Poothaa maathaa kee aasees.MP3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Saa veylaa parvaann jit satgur bheyttiaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Saaee gharhee sulakhannee simrat har naam.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Sabhai ghatt raam bolai - 1982.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Sakhi Vas Aaoo Sakhi 1982.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Satgur paaras parsiai.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Satgur shabad ujaaro deepaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Satgur sikh kaa halat palat savaarai.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Satguroo phurmaaiaa kaaree eyh kareyho.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Sathigur purakh milaae avagan vikanaa gun ravaa bal raam jeeo.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Satigur Dharasan Dhann Hai.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Sun Sun Jeevaa Soe Thinaa Kee.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Sunoh lokaa mai preym ras paaiaa - 1960s.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Tum badd daatey dey rahey.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Udam keeaa karaaiaa aarambh rachaaiaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Uddoh na kaagaa kaarey.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Ulaahano mai kaahoo na deeo.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Veeaah hoaa merey baabulaa.mp3",
  "http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Joginder Singh Talwara/Visar Naahee Daataar.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Aao sakhee har meyl kareyhaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Aithhai Othhai mukat hai jin raam pachhaaney%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Anoop padaarath naam sunoh%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Apney satgur kee vaddiaaee%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Baabaa man matvaaro%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Bin teyl deevaa kio jalai%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Eyk cheej mujhai deyh%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Gur parsaadee paaiaa jaaey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Gur saakhee jot jagaaey deeva baaliaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Gursikhaa jaikaar satgur paaiaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Ham hovat cheyree daas daasan kee%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Har gur naanak jin parasio%29-2.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Har pahilarhee laav parvirtee karam drirhaaiaa bal raam jeeo%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Jin har meetth lagaana%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Jinee sach vananjiaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Maaee ree man meyro matvaaro%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Man kio bairaag kurehigaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Man meyraa diaal seytee thir na rahai%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Meyraa man laagaa hai%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Meyree sakhee saheylarheeo%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Naam japandarhee laalee%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Saaee gharhee sulakhannee simrat har naam%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Satgur sikh kaa halat palat savaarai%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Satguroo phurmaaiaa kaaree eyh kareyho%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Udam keeaa karaaiaa aarambh rachaaiaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Ulaahano mai kaahoo na deeo%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Visar naahee daataar%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1960s %28Sunoh lokaa mai preym ras paaiaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1982 %28Meyra man laagaa hai raam piaarey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1982 %28Sabhai ghatt raam bolai%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1984 %28Bhaaee rey mo kau koee aaey milai har naam drirhaavai%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1986 %28Har key sang basey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1991 %28Har prabh kaaj rachaayaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-Hola Mahala %28Merey raam ham baarik har prabh key%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Pratan_Ludhiana_Smagam_Asso_Rae_Har_Ras_Meethaa.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Pratan_Ludhiana_Smagam_Saa_Vela_Parvaan.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_1982__Merra_Man_Lagaa_Hai_Raam_Payarrai.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_1982_Har_Gur_Nanak_Jin Parsyaio.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_1982_Sabhae_Ghat_Raam_Bollae.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_1982_Sakhi_Vas_Aaoo_Sakhi.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_Aasa_Ki_Vaar_Kirtan_Amritsar_1984 _2.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_and_Bhai_Tejinderpal_Singh_Jee_Dulla_-_Mera_Satgur_Pyara_Kit_Bid_Milai.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_India_1986_Part_2.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Aapeh meyl ley%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Amrit peevoh sadaa chir jeevoh%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Antar kapatt chukaavoh meyrey gursikhoh%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Aree baaee gobind naam mat beesrai%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Bhagtaa kee tteyk too%28n%29%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Eyh man naam nidhaan too paaey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Gur meyree poojaa gur gobind%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Gur saakhee antar jaagee%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Gurmukh laahaa lai gaey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Habh koorraavey kanm ikas saaee baaharey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Har anmrit paan karoh saadhsang%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Har gur naanak jin parasio%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Jaikaar keeo dharameeaa kaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Jin jan gurmukh seviaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Khaaey jeevoh sikh parvaar%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Mai man vaddee aas harey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Man meetth tuhaaro keeo%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Mat bhooleh rey man cheyt haree%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Meyraa satgur piaaraa kit bid miley%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Meyrey raam ham baarik har prabh key%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Saa veylaa parvaann jit satgur bheyttiaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Satgur shabad ujaaro deepaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Satguroo phurmaaiaa kaaree eyh kareyho%29-2.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Tum badd daatey dey rahey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Uddoh na kaagaa kaarey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh %28Veeaah hoaa merey baabulaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1960s %28Aiso sahaaee har ko naam%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1960s %28Uddoh na kaagaa kaarey%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1982 %28Meyree sakhee saheylarheeho prabh kai charann lageh%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1982 %28Sakhee aao sakhee vas aao sakhee%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1986 %28Har cheyt acheyt manaa%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-1990 %28Meyrey satgur apney baalak raakho%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-AntamSaskar.wmv",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhaaee Joginder Singh-Ludhiana %28Satgur paaras parsiai%29.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Pratan_Ludhiana_Smagam_Khayae_Jeevo_Sikh_Parvar.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Pratan_Ludhiana_Smagam_Sayee_Gharee_Sulakhani.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_1982_Aaoo_Sakhi_Har_Mail_Krayaeaa.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_1982_Lakh_Khusheaan_Patsheeaa.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_1982_Sakhee_Sahalarioo.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_1982_Tum_Vad Dattey_Deh_Rahey.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_Aasa_Ki_Vaar_Kirtan_Amritsar_1984_1.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Jee_Talwara_India_1986_Part_1.mp3",
  "https://www.ikirtan.com//Bhai_Joginder_Singh_Jee_Talwara/Bhai_Joginder_Singh_Talwara_Ludhiana_1980s.mp3",
]
const TALWARAJI_TRACK_NAMES=[
  "Aao sakhee har meyl kareyhaa.mp3",
  "Aapeh meyl ley.mp3",
  "Aeeh Sant Pauraneh.mp3",
  "Aiso sahaaee har ko naam - 1960s.mp3",
  "Aithhai Othhai mukat hai jin raam pachhaaney.mp3",
  "Amrit peevoh sadaa chir jeevoh.mp3",
  "Anand Karaj.mp3",
  "Anoop padaarath naam sunoh.mp3",
  "Antar kapatt chukaavoh meyrey gursikhoh.mp3",
  "Apney satgur kee vaddiaaee.mp3",
  "Aree baaee gobind naam mat beesrai.mp3",
  "Asso Rae Har Ras Meethaa - Ludhiana Smagam.mp3",
  "Baabaa man mathavaaro naam ras peevai.MP3",
  "Baabaa man matvaaro.mp3",
  "Bhaaee rey mo kau koee aaey milai har naam drirhaavai - 1984.mp3",
  "Bhagtaa kee tteyk toon.mp3",
  "Bin teyl deevaa kio jalai.mp3",
  "Eis grih mehi koee jaagath rehai.MP3",
  "Eyh man naam nidhaan too paaey.mp3",
  "Eyk cheej mujhai deyh.mp3",
  "Feekae har kae naam bin saadh.MP3",
  "Gur meyree poojaa gur gobind.mp3",
  "Gur parsaadee paaiaa jaaey.mp3",
  "Gur saakhee antar jaagee.mp3",
  "Gur saakhee jot jagaaey deeva baaliaa.mp3",
  "Gurmukh laahaa lai gaey.mp3",
  "Gursikhaa jaikaar satgur paaiaa.mp3",
  "Habh koorraavey kanm ikas saaee baaharey.mp3",
  "Ham hovat cheyree daas daasan kee.mp3",
  "Har anmrit paan karoh saadhsang.mp3",
  "Har cheyt acheyt manaa - 1986.mp3",
  "Har key sang basey - 1986.mp3",
  "Har prabh kaaj rachaaeiaa - Dehli Rainsbhai 1991.mp3",
  "Har Prabh Kaaj Rachaiaa.mp3",
  "Jaikaar keeo dharameeaa kaa.mp3",
  "Jin Har Meet Lagana - India 1980s.MP3",
  "Jin jan gurmukh seviaa.mp3",
  "Jinee sach vananjiaa.mp3",
  "Khaae Jeevahu Sikh Paravaar.mp3",
  "Khaaey jeevoh sikh parvaar.mp3",
  "Lakh Khusheaan Patsheeaa - 1982.mp3",
  "Maaee ree man meyro matvaaro.mp3",
  "Maeraa sathigur piaaraa kith bidhh milai.MP3",
  "Maeraa satigur piaaraa kith bidhh milai 2.mp3",
  "Mai man vaddee aas harey.mp3",
  "Man bairaagee kio n araadhhae - Delhi 2003.mp3",
  "Man kio bairaag kurehigaa.mp3",
  "Man meetth tuhaaro keeo.mp3",
  "Man meyraa diaal seytee thir na rahai.mp3",
  "Mat bhooleh rey man cheyt haree.mp3",
  "Meyraa man laagaa hai.mp3",
  "Meyree sakhee saheylarheeo.mp3",
  "Meyrey raam ham baarik har prabh key.mp3",
  "Meyrey satgur apney baalak raakho - 1990.mp3",
  "Naam japandarhee laalee.mp3",
  "Naam Ras Peevai - India 1980s.MP3",
  "Ouddahu n kaagaa kaarae - 1960s.mp3",
  "Poothaa maathaa kee aasees.MP3",
  "Saa veylaa parvaann jit satgur bheyttiaa.mp3",
  "Saaee gharhee sulakhannee simrat har naam.mp3",
  "Sabhai ghatt raam bolai - 1982.mp3",
  "Sakhi Vas Aaoo Sakhi 1982.mp3",
  "Satgur paaras parsiai.mp3",
  "Satgur shabad ujaaro deepaa.mp3",
  "Satgur sikh kaa halat palat savaarai.mp3",
  "Satguroo phurmaaiaa kaaree eyh kareyho.mp3",
  "Sathigur purakh milaae avagan vikanaa gun ravaa bal raam jeeo.mp3",
  "Satigur Dharasan Dhann Hai.mp3",
  "Sun Sun Jeevaa Soe Thinaa Kee.mp3",
  "Sunoh lokaa mai preym ras paaiaa - 1960s.mp3",
  "Tum badd daatey dey rahey.mp3",
  "Udam keeaa karaaiaa aarambh rachaaiaa.mp3",
  "Uddoh na kaagaa kaarey.mp3",
  "Ulaahano mai kaahoo na deeo.mp3",
  "Veeaah hoaa merey baabulaa.mp3",
  "Visar Naahee Daataar.mp3",
  "Bhaaee Joginder Singh %28Aao sakhee har meyl kareyhaa%29.mp3",
  "Bhaaee Joginder Singh %28Aithhai Othhai mukat hai jin raam pachhaaney%29.mp3",
  "Bhaaee Joginder Singh %28Anoop padaarath naam sunoh%29.mp3",
  "Bhaaee Joginder Singh %28Apney satgur kee vaddiaaee%29.mp3",
  "Bhaaee Joginder Singh %28Baabaa man matvaaro%29.mp3",
  "Bhaaee Joginder Singh %28Bin teyl deevaa kio jalai%29.mp3",
  "Bhaaee Joginder Singh %28Eyk cheej mujhai deyh%29.mp3",
  "Bhaaee Joginder Singh %28Gur parsaadee paaiaa jaaey%29.mp3",
  "Bhaaee Joginder Singh %28Gur saakhee jot jagaaey deeva baaliaa%29.mp3",
  "Bhaaee Joginder Singh %28Gursikhaa jaikaar satgur paaiaa%29.mp3",
  "Bhaaee Joginder Singh %28Ham hovat cheyree daas daasan kee%29.mp3",
  "Bhaaee Joginder Singh %28Har gur naanak jin parasio%29-2.mp3",
  "Bhaaee Joginder Singh %28Har pahilarhee laav parvirtee karam drirhaaiaa bal raam jeeo%29.mp3",
  "Bhaaee Joginder Singh %28Jin har meetth lagaana%29.mp3",
  "Bhaaee Joginder Singh %28Jinee sach vananjiaa%29.mp3",
  "Bhaaee Joginder Singh %28Maaee ree man meyro matvaaro%29.mp3",
  "Bhaaee Joginder Singh %28Man kio bairaag kurehigaa%29.mp3",
  "Bhaaee Joginder Singh %28Man meyraa diaal seytee thir na rahai%29.mp3",
  "Bhaaee Joginder Singh %28Meyraa man laagaa hai%29.mp3",
  "Bhaaee Joginder Singh %28Meyree sakhee saheylarheeo%29.mp3",
  "Bhaaee Joginder Singh %28Naam japandarhee laalee%29.mp3",
  "Bhaaee Joginder Singh %28Saaee gharhee sulakhannee simrat har naam%29.mp3",
  "Bhaaee Joginder Singh %28Satgur sikh kaa halat palat savaarai%29.mp3",
  "Bhaaee Joginder Singh %28Satguroo phurmaaiaa kaaree eyh kareyho%29.mp3",
  "Bhaaee Joginder Singh %28Udam keeaa karaaiaa aarambh rachaaiaa%29.mp3",
  "Bhaaee Joginder Singh %28Ulaahano mai kaahoo na deeo%29.mp3",
  "Bhaaee Joginder Singh %28Visar naahee daataar%29.mp3",
  "Bhaaee Joginder Singh-1960s %28Sunoh lokaa mai preym ras paaiaa%29.mp3",
  "Bhaaee Joginder Singh-1982 %28Meyra man laagaa hai raam piaarey%29.mp3",
  "Bhaaee Joginder Singh-1982 %28Sabhai ghatt raam bolai%29.mp3",
  "Bhaaee Joginder Singh-1984 %28Bhaaee rey mo kau koee aaey milai har naam drirhaavai%29.mp3",
  "Bhaaee Joginder Singh-1986 %28Har key sang basey%29.mp3",
  "Bhaaee Joginder Singh-1991 %28Har prabh kaaj rachaayaa%29.mp3",
  "Bhaaee Joginder Singh-Hola Mahala %28Merey raam ham baarik har prabh key%29.mp3",
  "Bhai_Joginder_Singh_Jee_Pratan_Ludhiana_Smagam_Asso_Rae_Har_Ras_Meethaa.mp3",
  "Bhai_Joginder_Singh_Jee_Pratan_Ludhiana_Smagam_Saa_Vela_Parvaan.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_1982__Merra_Man_Lagaa_Hai_Raam_Payarrai.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_1982_Har_Gur_Nanak_Jin Parsyaio.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_1982_Sabhae_Ghat_Raam_Bollae.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_1982_Sakhi_Vas_Aaoo_Sakhi.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_Aasa_Ki_Vaar_Kirtan_Amritsar_1984 _2.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_and_Bhai_Tejinderpal_Singh_Jee_Dulla_-_Mera_Satgur_Pyara_Kit_Bid_Milai.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_India_1986_Part_2.mp3",
  "Bhaaee Joginder Singh %28Aapeh meyl ley%29.mp3",
  "Bhaaee Joginder Singh %28Amrit peevoh sadaa chir jeevoh%29.mp3",
  "Bhaaee Joginder Singh %28Antar kapatt chukaavoh meyrey gursikhoh%29.mp3",
  "Bhaaee Joginder Singh %28Aree baaee gobind naam mat beesrai%29.mp3",
  "Bhaaee Joginder Singh %28Bhagtaa kee tteyk too%28n%29%29.mp3",
  "Bhaaee Joginder Singh %28Eyh man naam nidhaan too paaey%29.mp3",
  "Bhaaee Joginder Singh %28Gur meyree poojaa gur gobind%29.mp3",
  "Bhaaee Joginder Singh %28Gur saakhee antar jaagee%29.mp3",
  "Bhaaee Joginder Singh %28Gurmukh laahaa lai gaey%29.mp3",
  "Bhaaee Joginder Singh %28Habh koorraavey kanm ikas saaee baaharey%29.mp3",
  "Bhaaee Joginder Singh %28Har anmrit paan karoh saadhsang%29.mp3",
  "Bhaaee Joginder Singh %28Har gur naanak jin parasio%29.mp3",
  "Bhaaee Joginder Singh %28Jaikaar keeo dharameeaa kaa%29.mp3",
  "Bhaaee Joginder Singh %28Jin jan gurmukh seviaa%29.mp3",
  "Bhaaee Joginder Singh %28Khaaey jeevoh sikh parvaar%29.mp3",
  "Bhaaee Joginder Singh %28Mai man vaddee aas harey%29.mp3",
  "Bhaaee Joginder Singh %28Man meetth tuhaaro keeo%29.mp3",
  "Bhaaee Joginder Singh %28Mat bhooleh rey man cheyt haree%29.mp3",
  "Bhaaee Joginder Singh %28Meyraa satgur piaaraa kit bid miley%29.mp3",
  "Bhaaee Joginder Singh %28Meyrey raam ham baarik har prabh key%29.mp3",
  "Bhaaee Joginder Singh %28Saa veylaa parvaann jit satgur bheyttiaa%29.mp3",
  "Bhaaee Joginder Singh %28Satgur shabad ujaaro deepaa%29.mp3",
  "Bhaaee Joginder Singh %28Satguroo phurmaaiaa kaaree eyh kareyho%29-2.mp3",
  "Bhaaee Joginder Singh %28Tum badd daatey dey rahey%29.mp3",
  "Bhaaee Joginder Singh %28Uddoh na kaagaa kaarey%29.mp3",
  "Bhaaee Joginder Singh %28Veeaah hoaa merey baabulaa%29.mp3",
  "Bhaaee Joginder Singh-1960s %28Aiso sahaaee har ko naam%29.mp3",
  "Bhaaee Joginder Singh-1960s %28Uddoh na kaagaa kaarey%29.mp3",
  "Bhaaee Joginder Singh-1982 %28Meyree sakhee saheylarheeho prabh kai charann lageh%29.mp3",
  "Bhaaee Joginder Singh-1982 %28Sakhee aao sakhee vas aao sakhee%29.mp3",
  "Bhaaee Joginder Singh-1986 %28Har cheyt acheyt manaa%29.mp3",
  "Bhaaee Joginder Singh-1990 %28Meyrey satgur apney baalak raakho%29.mp3",
  "Bhaaee Joginder Singh-AntamSaskar.wmv",
  "Bhaaee Joginder Singh-Ludhiana %28Satgur paaras parsiai%29.mp3",
  "Bhai_Joginder_Singh_Jee_Pratan_Ludhiana_Smagam_Khayae_Jeevo_Sikh_Parvar.mp3",
  "Bhai_Joginder_Singh_Jee_Pratan_Ludhiana_Smagam_Sayee_Gharee_Sulakhani.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_1982_Aaoo_Sakhi_Har_Mail_Krayaeaa.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_1982_Lakh_Khusheaan_Patsheeaa.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_1982_Sakhee_Sahalarioo.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_1982_Tum_Vad Dattey_Deh_Rahey.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_Aasa_Ki_Vaar_Kirtan_Amritsar_1984_1.mp3",
  "Bhai_Joginder_Singh_Jee_Talwara_India_1986_Part_1.mp3",
  "Bhai_Joginder_Singh_Talwara_Ludhiana_1980s.mp3",
]
